---

- name: npm | Install the `nodejs-legacy` and `npm` package
  apt: pkg={{ item }}
  with_items:
    - nodejs-legacy
    - npm

- name: npm | Install npm latest version
  npm: name=npm state=present global=yes

- name: npm | install npm packages
  npm: >
    name={{ item.name }}
    state=present
    global=yes
    version={{ item.version }}
  with_items: npm_packages
  when: npm_packages is defined and item.name is defined and item.version is defined
  become: yes

